import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/global.scss";

const inter = localFont({
  src: "../assets/fonts/Inter.ttf",
  variable: "--fundr-base-font",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>{children}</body>
    </html>
  );
}
